from gahenax_spy_system.agents.seed_auditor import SeedAuditor

def generate_full_map_js():
    server_seed = "f4f906b6d7c8434dd24e6d223b7081d3db20fcb2b9e5a6958a40deb8faa8a629"
    client_seed = "wERGyEJcrry31PqffCXlioCoT1QB4IlKOI2lakZI1fnDtzFBzVFbVltJMXPwVVvF"
    
    auditor = SeedAuditor()
    wins = []
    big_wins = []
    
    for nonce in range(1, 501):
        res = auditor.verify(server_seed, client_seed, nonce)
        num = res["result_number"]
        if num > 90.0:
            big_wins.append(nonce)
        elif num > 49.5:
            wins.append(nonce)
            
    print("// --- DATA GENERATED BY GAHENAX ---")
    print(f"const WINS = {wins};")
    print(f"const BIG_WINS = {big_wins};")

if __name__ == "__main__":
    generate_full_map_js()
